name: Deploy to Production

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup deploy key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan productionserver.be >> ~/.ssh/known_hosts
          
      - name: Deploy to server
        run: |
          rsync -avz --exclude '.git/' \
                     --exclude '.github/' \
                     --exclude 'node_modules/' \
                     --exclude '.env' \
                     --exclude '.env.example' \
                     ./ productionserverbe@ssh.productionserver.be:www/massimo/
          
      - name: Post-deployment commands
        run: |
          ssh productionserverbe@ssh.productionserver.be "cd www/massimo && bash post-deploy.sh"